python train.py --load_model "myfolder/models/rwkv7-g1-0.4b-20250324-ctx4096.pth" \
 --wandb "RWKV-LM-RLHF x070M Experiment" --proj_dir "myfolder/Outputs/x070m-memorytuning-stage2" \
 --load_adapter "myfolder/Outputs/x070m-memorytuning/rwkv-2.pth" \
 --vocab_size 65536 --ctx_len 8192 \
 --epoch_steps 1000 --epoch_count 200 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 3 --n_layer 24 --n_embd 1024 \
 --lr_init 1e-4 --lr_final 1e-6 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision 'bf16' \
 --grad_cp 1 --my_testing "x070m" \
 --strategy deepspeed_stage_1 \
 --layer_profile 'layerprofile/24_TEST_nm_stage2.csv' \
 --quant 0 \
 --quant_mode 'int8'\
 --gpu_arch 'cuda' \
 --limited_lora 0 \
 --sft 1 \
 --sft_jsonmode 1 \
 --sft_jsonmode_tokenizermode 'world' \
 --smoothing 0.005 \
 --random_mode 1 \
 --infctx_dataset_multiplier 16 \
 --optim 'muon' \
 --train_data_file 'myfolder/new_dataset_format' \
 --accumulate_grad_batches 1
