python train.py --load_model "myfolder/models/rwkv-x070-2b9-world-v3-preview-20250210-ctx4k.pth" \
 --wandb "RWKV-LM-RLHF x070 2b9 nsha" --proj_dir "myfolder/Outputs/x070-nsha" \
 --vocab_size 65536 --ctx_len 4096 \
 --epoch_steps 500 --epoch_count 200 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 1 --n_layer 32 --n_embd 2560 \
 --lr_init 1e-4 --lr_final 1e-6 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision 'bf16' \
 --grad_cp 1 --my_testing "x070" \
 --strategy deepspeed_stage_2_offload \
 --layer_profile 'layerprofile/32_TEST_State.csv' \
 --quant 1 \
 --state 1 \
 --quant_mode 'fp8'\
 --gpu_arch 'triton' \
 --limited_lora 0 \
 --sft 1 \
 --sft_jsonmode 1 \
 --sft_jsonmode_tokenizermode 'world' \
 --smoothing 0.001 \
 --random_mode 1 \
 --infctx_dataset_multiplier 1 \
 --optim '' \
 --train_data_file 'myfolder/nsha_dataset' \
 --accumulate_grad_batches 1
