python train.py --load_model "models/x060-6B-prune.pth" \
 --load_adapter "6B-distillation1/rwkv-0.pth" \
 --wandb "RWKV-LM-RLHF State Reverse Distillation" --proj_dir "6B-SRD-test" \
 --vocab_size 65536 --ctx_len 2048 \
 --epoch_steps 250 --epoch_count 1000 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 3 --n_layer 25 --n_embd 4096\
 --lr_init 1e-5 --lr_final 1e-6 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision bf16 \
 --grad_cp 1 --my_testing "x060" \
 --strategy deepspeed_stage_2 \
 --layer_profile 'layerprofile/25_TEST.csv' \
 --quant 1 \
 --quant_mode 'int8'\
 --gpu_arch 'cuda' \
 --limited_lora 0 \
 --distillation 1 \
 --temperature 2.5 \
 --top_k 100 \
 --alpha 0.5 \
 --smoothing 0.01 \
 --distillation_train_file 'datasets/test.h5'
