python train.py --load_model "myfolder/models/LLMJP-RWKV7B2.pth" \
 --wandb "RWKV-LM-RLHF xa070 llm-jp-7B2 linearize" --proj_dir "myfolder/Outputs/llmjp7b2" \
 --vocab_size 99584 --ctx_len 4096 \
 --head_size_a 64 \
 --epoch_steps 1000 --epoch_count 200 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 1 --n_layer 32 --n_embd 4096 --dim_ffn 11008 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision 'bf16' \
 --grad_cp 1 --my_testing "xa070" \
 --strategy deepspeed_stage_2_offload \
 --layer_profile 'layerprofile/32_TEST_dora.csv' \
 --fla 0 \
 --infctx 0 \
 --state 0 \
 --quant 1 \
 --quant_mode 'int8'\
 --gpu_arch 'cuda' \
 --limited_lora 0 \
 --sft 1 \
 --smoothing 0.005 \
 --random_mode 1 \
 --infctx_dataset_multiplier 8 \
 --optim 'AdamW8bit' \
 --train_data_file 'myfolder/2024_dataset/General3_llama_llmjp.h5' \
 --accumulate_grad_batches 4
