python train.py --load_model "myfolder/models/RWKV7-G1-2.9B-87%25trained-20250511-ctx4k.pth" \
 --wandb "RWKV-LM-RLHF x070 2.9B T-BPTT May Kirihara Remaster" --proj_dir "myfolder/Outputs/x070-tbptt-maykirihara-2b9" \
 --vocab_size 65536 --ctx_len 65536 \
 --chunk_ctx 4096 \
 --infctx 1 \
 --epoch_steps 100 --epoch_count 200 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 3 --n_layer 32 --n_embd 2560 \
 --lr_init 1e-4 --lr_final 1e-6 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision 'bf16' \
 --grad_cp 1 --my_testing "x070" \
 --strategy deepspeed_stage_2 \
 --layer_profile 'layerprofile/32_TEST_lora.csv' \
 --quant 1 \
 --quant_mode 'int8'\
 --gpu_arch 'cuda' \
 --limited_lora 0 \
 --sft 1 \
 --sft_jsonmode 1 \
 --sft_jsonmode_tokenizermode 'world' \
 --smoothing 0.005 \
 --random_mode 1 \
 --infctx_dataset_multiplier 32 \
 --optim 'muon' \
 --train_data_file 'myfolder/kirihara/Output' \
 --accumulate_grad_batches 1
