python train.py --load_model "myfolder/models/rwkv7-g1-2.9b-20250519-ctx4096.pth" \
 --wandb "RWKV-LM-RLHF x070 2.9B Hidden Offset" --proj_dir "myfolder/Outputs/x070-2b9-pre" \
 --vocab_size 65536 --ctx_len 4096 \
 --epoch_steps 1000 --epoch_count 200 --epoch_begin 0 --epoch_save 1 \
 --micro_bsz 1 --n_layer 32 --n_embd 2560 \
 --lr_init 1e-4 --lr_final 1e-6 \
 --warmup_steps 100 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 \
 --accelerator gpu --devices 1 --precision 'bf16' \
 --grad_cp 1 --my_testing "x070" \
 --strategy deepspeed_stage_1 \
 --layer_profile 'layerprofile/32_TEST_State.csv' \
 --quant 0 \
 --quant_mode 'int8'\
 --gpu_arch 'triton' \
 --limited_lora 1 \
 --state 1 \
 --prefix_tuning 1 \
 --prefix_token_len 1024 \
 --direct_state_tuning 0 \
 --post_wkv_tuning 0 \
 --sft 1 \
 --sft_jsonmode 1 \
 --sft_jsonmode_tokenizermode 'world' \
 --smoothing 0.005 \
 --random_mode 1 \
 --infctx_dataset_multiplier 1 \
 --optim 'muon' \
 --train_data_file 'myfolder/new_dataset_nsfw' \
 --accumulate_grad_batches 1
